### PR TITLE
Update coord conver

### PR DESCRIPTION
**Pull request by JintaoWu98**
Modification in ARC/ipython/Tools/coordinates conversions.ipynb

1. Improved path of example for xyz_to_str
2. Replaced wrong zmat_to_xyz in conversions example 
3. Added test_coordinates_converter_tools_notebook to converter

### CODE REVIEW

**Comment by alongd** [comment]
@JintaoWu98, the tests fail due to a mismatch of the very last digits in the coords, see [here](https://github.com/ReactionMechanismGenerator/ARC/actions/runs/5857088399/job/15878160850?pr=692#step:28:591).
Try to use [this function](https://github.com/ReactionMechanismGenerator/ARC/blob/main/arc/common.py#L953) for the comparison in the test.

**Comment by JintaoWu98** [comment]
> @JintaoWu98, the tests fail due to a mismatch of the very last digits in the coords, see [here](https://github.com/ReactionMechanismGenerator/ARC/actions/runs/5857088399/job/15878160850?pr=692#step:28:591). Try to use [this function](https://github.com/ReactionMechanismGenerator/ARC/blob/main/arc/common.py#L953) for the comparison in the test.

Got it! Thanks! I will try and fix it again.

**Comment by alongd** [comment]
@JintaoWu98, looking great, thanks!!
Could you please squash the two last commit together, and also rebase this branch?

**Review by alongd — APPROVED** [review]
Thank you @JintaoWu98 for this contribution!

**Pull request merged**
