### PR TITLE
installation corrected, from source activate to conda activate

### PR DESCRIPTION
**Pull request by kfir4444**
corrected the docs for
conda activate arc_env

### CODE REVIEW

**Comment by mefuller** [comment]
So I have been chasing my tail on this - every time I fix something, another test is failing.
Is something broken in my environment? Are the tests passing somewhere? @alongd @kfir4444 ?

Regarding the specific failure observed here, the issue is that values differ in the 4th decimal place while `assertAlmostEqual` dy default is looking to the 7th decimal place - easy fix to specify three decimal places.
However, as soon as I fix that, I get more errors*:
```
======================================================================
FAIL: Test parsing a 1D scan output file
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fuller/Code/ARC/arc/parserTest.py", line 372, in test_parse_1d_scan_energies
    self.assertEqual(energies_2, None)
AssertionError: array([0.]) != None

======================================================================
FAIL: Test the get_family() function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fuller/Code/ARC/arc/rmgdbTest.py", line 98, in test_get_family
    self.assertIsInstance(family_1, KineticsFamily)
AssertionError: None is not an instance of <class 'rmgpy.data.kinetics.family.KineticsFamily'>

======================================================================
FAIL: Test Open Babel force field on RDKit conformers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fuller/Code/ARC/arc/species/conformersTest.py", line 589, in test_openbabel_force_field_on_rdkit_conformers
    self.assertAlmostEqual(energies[1], -0.702848, 5)
AssertionError: -0.6990512842794496 != -0.702848 within 5 places (0.003796715720550403 difference)
```
For the first one, if I fix it I get a nearly identical error next about angles: either the expected values for angle and energy in the test need to change from `None` to `0.` and `360.`, respectively, or the 1D scan function in `RMG-Py/arkane/ess/gaussian.py` needs to be modified to return `None` for both energy and angle on single value arrays (not unreasonable as a scan should have at least two points).

The next two errors I haven't gotten to yet and I don't think I should until I know if my setup is broken or if there is a known good state.

*The current behavior of `make test` to me seems aberrant for two reasons: first, testing terminates after a small number of failed tests without having run all tests (or reaching some huge number of errors). Second, there's no skipping of up-to-date tests, so after I fix one or two tests, I have to sit through ten minutes of testing again to check the full suite. I'll try to work on this issue of how testing functions since I think that has the potential to be a real time suck going forward.

**Comment by mefuller** [comment]
I pushed my branch and opened a draft PR #481 so that we can all see what progress has been made

**Comment by alongd** [comment]
Thanks. Let me know if I'm needed for something specific

**Comment by kfir4444** [comment]
I advanced in conformersTest.py, now we get another error regarding chiralities, which requires a further look.

**Comment by mefuller** [comment]
I don't recall any errors there today. Are you sure all your sources are up to date?

On 9 December 2021 14:12:27 GMT+02:00, kfir4444 ***@***.***> wrote:
>I advanced in conformersTest.py, now we get another error regarding
>chiralities, which requires a further look.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ReactionMechanismGenerator/ARC/pull/480#issuecomment-989796058

Mark E. Fuller, Ph.D.
HaShikma 19, Apt. 24
Nesher 3681219, Israel
+972 (0)53-872-6579
+49 (0)1577 1848188
+1 401-236-4526
***@***.***
***@***.***
***@***.***
@mefuller:matrix.org
https://www.stossrohr.net
PGP Fingerprint: 73F1 A30C BDF4 DB4B C75F FD0F D599 E76C FFCA BF60

**Comment by alongd** [comment]
@kfir4444, could you rebase and force push?

**Comment by kfir4444** [comment]
@alongd Done :)

**Review by alongd — APPROVED** [review]
Thanks!

**Pull request merged**
