### PR TITLE
Minor: Fixed explanatory comments when setting the submit file memory

### PR DESCRIPTION
**Pull request by alongd**

### CODE REVIEW

**Comment by kfir4444** [comment]
thanks @alongd!
Could you address the codecov comment, and add additional context?

**Review by kfir4444 — COMMENTED** [review]
Thanks @alongd,
Could you maybe add a test for your changes?

**Comment by alongd** [comment]
@kfir4444, I just updated comments, not code, so I don't think tests are needed. Let me know if I misunderstood

**Review by kfir4444 — APPROVED** [review]
Thanks @alongd!
Looks great!

**Pull request merged**
