### PR TITLE
BugFix: cannot save image when using notebook

### PR DESCRIPTION
**Pull request by xiaoruiDong**
`plt.show()` clears the whole thing, so anything afterwards will happen on a new empty figure

### CODE REVIEW

**Comment by alongd** [comment]
Thanks, the code looks good!
Can you change the commit message to `BugFix: Correctly save an image when using a notebook`?

**Comment by xiaoruiDong** [comment]
The check failed is not related to this PR change. I think it is because of the transition to ESSfactory of Arkane.

**Comment by alongd** [comment]
No problem, we'll wait until #367 is merged (it's the next one on the merging queue), then we'll rebase all other PRs

**Comment by xiaoruiDong** [comment]
@alongd Sure!

**Comment by alongd** [comment]
@xiaoruiDong, please rebase

**Comment by xiaoruiDong** [comment]
@alongd checks done.

**Pull request merged**
