### PR TITLE
Automatic node test and swtich for errored jobs on OGE

### PR DESCRIPTION
**Pull request by oscarwumit**
ARC now performs automatic node test and switch for errored jobs on OGE server (currently implemented for Pharos). 

Features highlight:

1. ARC now provides detailed job status for OGE cluster. For detailed queue status and state codes explanation, see:
"https://softpanorama.org/HPC/Grid_engine/Queues/queue_states.shtml"

2. Added scripts.py to better organize ARC scripts

### CODE REVIEW

**Comment by oscarwumit** [comment]
This PR requires commit 7856047 "Allow users to specify the number of cpu's to use per server" to function properly.

**Comment by alongd** [comment]
Can you rebase?

**Comment by alongd** [comment]
@oscarwumit, what's the status of this PR?

**Comment by oscarwumit** [comment]
I will rebase it soon. Need some change. @alongd

**Pull request closed without merging**
