### PR TITLE
Add option for running all optimizations as fine

### LINKED ISSUE #303: Add option to only perform a fine optimization
**Is your feature request related to a problem? Please describe.**
Usually, when one uses ARC, they need ARC to start from the very beginning and generate a plausible conformer for the molecule, and then use progressively higher levels of theory to optimize this geometry.

However, this is not always the case. For example, it is possible that the user has a very good geometry for the molecule already (for example, perhaps they have already performed a calculation for this species using a good DFT functional, but want to compare with another method). In this case, the user does not want to waste any computational time by starting from the very beginning.

ARC is fairly accommodating for this. For example, you can tell ARC not to perform conformer searches. One thing that ARC does not currently let you do though is bypass an initial optimization step before performing a fine optimization. *Ideally, the user should be able to tell ARC to go directly to the fine optimization in the event that they think the geometry supplied is very close.*

**Describe the solution you'd like**
I would like to add a keyword to ARC's input file called `fine_only` that if `True` will only perform a fine optimization.

**Additional context**
I am planning on implementing this myself, but I would appreciate any guidance as to which parts of ARC will likely need changing, as well as any comments about how this feature should best be implemented to best align with the vision for ARC going forward (if it is a feature that should be implemented in the first place).

### PR DESCRIPTION
**Pull request by amarkpayne**
fixes #303 

I found a solution that implements the option to run all optimizations as fine, and after testing it appears to work. It is sort of a hack around though, so let me know if there is a better way so that the flow of the code remains clear.

### CODE REVIEW

**Comment by alongd** [comment]
I see. Let me know what you think about the comment in #303? In general I think we should avoid accumulating case-specific arguments in main.

**Comment by alongd** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- arc/main.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ReactionMechanismGenerator/ARC/pullRequest?prid=4961352&bid=16393288)

**Comment by amarkpayne** [comment]
I implemented your idea that if `fine == True` but `opt == False` that it would run optimizations using a fine level only. I wanted to implement this entirely in scheduler.py, but I ran into some problems because if `opt == False` functions in main.py such as `determine_model_chemistry_for_job_types` do not function properly. Instead of trying to go into these functions and add/modify if statements to catch these cases, I instead thought it would be more simplistic to set a `fine_only` attribute on the main ARC object, and if true, set `self.job_types['opt'] = True` so that the rest of the code behaves as expected.

This means that the ARC object gained an extra attribute (which is unfortunate) but it does avoid adding on syntax to the ARC input file as requested (i.e. fine_only is an attribute but not an argument of `__init__`). Let me know if this is acceptable to you. If not then we will have to do some searching to see where we need to add/modify statements that check both opt == True and fine == True.

Finally, I added some documentation for this feature, along with fixing a few typos that I found.

**Comment by alongd** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/ReactionMechanismGenerator/ARC/pullRequest?prid=4961352&bid=16393288)

**Comment by amarkpayne** [comment]
@alongd Are there any other changes you would like me to make?

**Comment by alongd** [comment]
Do you think it'll work if instead of adding a new attribute ('fine_only') to Scheduler, we do the following?
```python
def run_opt_job(self, label):
    if 'opt' not in self.job_dict[label]:  # Check whether or not opt jobs have been spawned yet
        # we're spawning the first opt job for this species
        self.job_dict[label]['opt'] = dict()
    if self.species_dict[label].initial_xyz is None:
        raise SpeciesError(f'Cannot execute opt job for {label} without xyz (got None for Species.initial_xyz)')
    fine = self.job_types['fine'] and not self.job_types['opt']
    self.run_job(label=label, xyz=self.species_dict[label].initial_xyz, level_of_theory=self.opt_level,
                 job_type='opt', fine=fine)
```

**Comment by amarkpayne** [comment]
> Do you think it'll work if instead of adding a new attribute (`fine_only`) to Scheduler, we do the following?
> 
> ```python
> def run_opt_job(self, label):
>     if 'opt' not in self.job_dict[label]:  # Check whether or not opt jobs have been spawned yet
>         # we're spawning the first opt job for this species
>         self.job_dict[label]['opt'] = dict()
>     if self.species_dict[label].initial_xyz is None:
>         raise SpeciesError(f'Cannot execute opt job for {label} without xyz (got None for Species.initial_xyz)')
>     fine = self.job_types['fine'] and not self.job_types['opt']
>     self.run_job(label=label, xyz=self.species_dict[label].initial_xyz, level_of_theory=self.opt_level,
>                  job_type='opt', fine=fine)
> ```

Although I agree that I would like to get rid of the flag, I am unsure if this solution will work because the function `run_opt_job` is usually only called if `self.job_types['opt']` is True. But if `self.job_types['opt']` is True how do we determine if we should run only fine optimizations?

There may be a solution here, but the limiting factor here is that a lot of code that needs to be run for ANY type of optimization job to work requires that `self.job_types['opt']` be True as far back as `arc/main.py` even before the scheduler is called. 

A possible solution would be to make ARC additionally check for `self.job_types['fine']` whenever it needs to determine if any type of opt job needs to be run, but then we will have to be careful to always code ARC this way going forward (i.e. this could be an easy vector for bugs to be introduced that could unnoticed for awhile unless we had a good functional test for fine optimizations).

An interesting solution would be to have these job types be classes in ARC, and have a fine job subclass an opt job class, but that would involve a lot of re-writing of course.

Perhaps we can discuss this more offline.

**Comment by alongd** [comment]
OK. Could you rebase?

**Comment by amarkpayne** [comment]
Done! Let me know if there is anything else I need to do.

**Pull request merged**
